/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication1;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import static javax.swing.text.html.parser.DTDConstants.SYSTEM;
//çağkan çalışır
/**
 *
 * @author cagka
 */
public class game extends javax.swing.JFrame {
    int pcvalue=0,pcvaluefordecide=0;
    int tahmin1=0,t=0;
    int ilkt = 0;
    int ilkb=0;
    int stahpcbirlerbasamak=0;
    int  stahpconlarbasamak=0;
    int stahpcyüzlerbasamak=0;
    int  stahpcbinlerbasamak=0;
    int  tahpcbirlerbasamak = 0;int  tahpconlarbasamak=0;int  tahpcyüzlerbasamak = 0;int  tahpcbinlerbasamak=0;
    int ipucupctahmin;
    String tahmin2;
    int sonsayı;
    

    /**
     * Creates new form game
     */
    public game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tahmin Bul");
        setBackground(new java.awt.Color(208, 173, 139));
        setResizable(false);

        jLabel1.setText("4 Basamaklı Sayı Tahmin Oyunu");

        jLabel2.setText("Tahmininizi Giriniz:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Kontrol ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Rastgele Pc Sayısı Üret");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Bilgilendirme");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButton3)))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(41, 41, 41)
                                .addComponent(jButton2))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
      
      
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Basamak basamk kontrol işlemi do
       if(pcvalue==0){
         Random rnd=new Random();
         pcvalue = rnd.nextInt(8999) + 1000;
       }
        int pcbirlerbasamak,pconlarbasamak,pcyüzlerbasamak,pcbinlerbasamak;
        pcbirlerbasamak=pcvalue%10;
        pconlarbasamak=pcvalue%100/10;
        pcyüzlerbasamak=pcvalue%1000/100;
        pcbinlerbasamak=pcvalue%10000/1000;
            
        tahmin1= Integer.parseInt(jTextField1.getText());
         int kulbirlerbasamak=tahmin1%10;
         int kulconlarbasamak=tahmin1%100/10;
         int kulyüzlerbasamak=tahmin1%1000/100;
         int kulbinlerbasamak=tahmin1%10000/1000;
         int ipucupozitif=0,ipucunegatif=0;
         
     try{
       if(pcvalue!=0 &&jTextField1.getText()!=""){  
       
        if(tahmin1==pcvalue){
            //ekrana bildiğinde basım işlemi yapılmaktadır.
             JOptionPane.showMessageDialog(null, "Tebrikler"+tahmin1+pcvalue, "Bildiniz" , JOptionPane.INFORMATION_MESSAGE);
         
        }   else{//ipucu için basamak karşılaştırılmaları 
                if(pcbirlerbasamak==kulbirlerbasamak){
                ipucupozitif++;
                }   else{
                ipucunegatif++;
                }
                    if(kulconlarbasamak==pconlarbasamak){
                        ipucupozitif++;
                
                    }else{
                        ipucunegatif++;
                    }
                        if(kulyüzlerbasamak==pcyüzlerbasamak){
                        ipucupozitif++;
                
                        }   else{
                            ipucunegatif++;
                        }
                            if(kulbinlerbasamak==pcbinlerbasamak){
                                ipucupozitif++;
                
                                }
                                else{
                                    ipucunegatif++;
                                  }
                                   
                                       
                                    
            
        JOptionPane.showMessageDialog(null, "+"+ipucupozitif+",-"+ipucunegatif, "İpucu" , JOptionPane.INFORMATION_MESSAGE);
      if(pcvaluefordecide==0){
      Random rnd=new Random();
      pcvaluefordecide = rnd.nextInt(8999) + 1000;
       
      
      }
      tahmin2= JOptionPane.showInputDialog("Bilgisayar tahmini:"+pcvaluefordecide+"Lütfen Tutmuş olduğunuz sayıyla pc tahmini arasındaki tutan rakam sayısını giriniz:");
        ipucupctahmin=Integer.parseInt(tahmin2);
       
       
         int basarısız=4-ipucupctahmin;
       
       
       System.out.println("+"+ipucupctahmin+"-"+basarısız);
       int i=1;
       if(i==1&&ipucupctahmin>0){
         tahpcbirlerbasamak=pcvaluefordecide%10;
         tahpconlarbasamak=pcvaluefordecide%100/10;
         tahpcyüzlerbasamak=pcvaluefordecide%1000/100;
         tahpcbinlerbasamak=pcvaluefordecide%10000/1000;
         ilkt=ipucupctahmin;
         ilkb=basarısız;
        i++;
       }  
       
       if(t>0){
           
          Random rnd=new Random();
          pcvaluefordecide = rnd.nextInt(8999) + 1000;
          stahpcbirlerbasamak=pcvaluefordecide%10;
          stahpconlarbasamak=pcvaluefordecide%100/10;
          stahpcyüzlerbasamak=pcvaluefordecide%1000/100;
          stahpcbinlerbasamak=pcvaluefordecide%10000/1000;
             pcvaluefordecide=(pcvaluefordecide-stahpcbirlerbasamak)+tahpcbirlerbasamak;
             pcvaluefordecide = rnd.nextInt(8999) + 1000;
             pcvaluefordecide=(pcvaluefordecide-stahpcbinlerbasamak)+tahpcbinlerbasamak;
             pcvaluefordecide = rnd.nextInt(8999) + 1000;
             pcvaluefordecide=(pcvaluefordecide-stahpcyüzlerbasamak)+tahpcyüzlerbasamak;
             pcvaluefordecide = rnd.nextInt(8999) + 1000;
             pcvaluefordecide=(pcvaluefordecide-stahpconlarbasamak)+tahpconlarbasamak;
             pcvaluefordecide = rnd.nextInt(8999) + 1000;
       
      }
      t++;
         
         
         Random rnd=new Random();
          pcvaluefordecide = rnd.nextInt(8999) + 1000;
        
    
        if(ipucupctahmin==4){  
          JOptionPane.showMessageDialog(null, "Bilgisayar Doğru tahmin etti", "Oyun için tekrar açınız." , JOptionPane.INFORMATION_MESSAGE);
             System.exit(0);//oyun bitti cıkıs
        }
      
           
       
        
        }
       }
       else{
           if(jTextField1.getText()==""){
             JOptionPane.showMessageDialog(null, "Tahminde bulunuz.", "Uyarı" , JOptionPane.INFORMATION_MESSAGE);
           }
           if(pcvalue==0){
             JOptionPane.showMessageDialog(null, "Rastgele Sayı üret butonuna basınız.", "Uyarı" , JOptionPane.INFORMATION_MESSAGE);
           }
       }
         
   }catch(Exception e){
    }
     t++;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Oyun Hakkında Nasıl işleyiceği ne işlemler olacagı hakkında bilgi verir;
        String msj="  Bilgisayar ile Kullanıcı 4 basamaklı sayılar tutacaktır.Kullanıcı bilgisayarın 4 basamaklı sayısını tahmin etmeye çalışcaktır.\nİpuçları verilcektir.Eğer tahmin edilen sayı içinde tutulan sayının rakamlarından varsa ve basamak değeri doğruysa “+” değer olarak ipucu verilecek, basamak değeri yanlış ise “-” değer ipucu olarak verilecektir.\n Örneğin bilgisayar 5483 sayısını tutsun ve kullanıcı 3468 tahmini yaptığında 4 sayısının basamak değeri doğru olduğu için +1, 3 ve 8 sayısının basamak değeri yanlış olduğu için -2 değeri dönülecektir.Bir kere en az Rastgele Pc sayısına ürete basılmalıdır.";
        JOptionPane.showMessageDialog(null, msj, "Bilgilendirme" , JOptionPane.INFORMATION_MESSAGE);          
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // Random 4 basamaklı kullanıcının tahmin etmesi için sayı üretilmektedir.Bu sayı kullanıcı tarafından tahmin edilmeye çalışılcaktır
       Random rnd=new Random();
       pcvalue = rnd.nextInt(8999) + 1000;
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
